### ISSUE TITLE
开发了目前官方并没有提供的中介度算法，是否可以提交，该以何种demo格式提交？

### ISSUE THREAD

**Issue by calvinxhk** [tigergraph/gsql-graph-algorithms#14]
根据自己的schema （异质图，但是业务场景可以看做是同质图）开发了无加权 的中介度算法，

**Comment by summerrain1994** [comment]
> 根据自己的schema （异质图，但是业务场景可以看做是同质图）开发了无加权 的中介度算法，

Create New File -> Save -> Pull Request
