### ISSUE TITLE
issues in louvain parallel

### ISSUE THREAD

**Issue by dreamerlzl** [tigergraph/gsql-graph-algorithms#2]
I have two vertex types,  user and player. When I try to install the Louvain Method with Parallelism and Refinement for the vertex type user only, it says this:
Type Check Error in query louvain_parallel_file (TYP-162): line 227, col 16
'S' is initialized to vertex type (vt) [user], but the new DML block produces vt
[user, player], which is not a subset of the initial vts.
I have viewed the source but I still don't know how to fix this.
Thanks for any suggestion!

**Comment by Suxiaocai** [comment]
Are you traversing on all edges? It seems that S is initialized to take user type of vertex, but then after traversal you also add player type of vertices in it. If you want to run louvain on user, then the edges used in the algorithm should be from user to user, not from user to other vertex types.

**Comment by emperorz** [comment]
louvain_parallel is missing the template file, so cannot be installed.

**Comment by Boyu1997** [comment]
louvain_parallel is updated by https://github.com/tigergraph/gsql-graph-algorithms/pull/41
